"""Emit folded MLP weights as a C source file for the 6844 MSS (R5F).

Weights land in `.rodata.pose_model`, which linker.cmd pins to TCMB_RAM.  They
must NOT go to TCMA: after the Phase 1 cubeQuery patch TCMA has ~5.8 KB free,
and this table is ~51 KB.  TCMB has 256 KB and already hosts the relocated
classifier stack (FIX2, see the fallsm-boot-bug memory).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from .dataset import (CLASS_NAMES, FEATURE_COUNT, FEATURE_NAMES, INPUT_SIZE,
                      MIN_POINTS, WINDOW_SIZE)

SECTION = "__attribute__((section(\".rodata.pose_model\")))"


def _arr(name: str, a: np.ndarray) -> str:
    """Row-major float32 C array. Row-major matches the firmware's dot loop."""
    flat = a.reshape(-1).astype(np.float32)
    body = []
    for i in range(0, flat.size, 8):
        body.append("    " + " ".join(f"{v:+.8e}f," for v in flat[i:i + 8]))
    dims = "".join(f"[{d}]" for d in a.shape)
    return (f"{SECTION}\nconst float {name}{dims} = {{\n"
            + "\n".join(body) + f"\n}};   /* {flat.size} floats, {flat.nbytes} B */\n")


def write_c(path: Path, layers, acc: float | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tot = sum(W.size + b.size for W, b in layers)
    sizes = [layers[0][0].shape[1]] + [W.shape[0] for W, _ in layers]

    h = [
        "/*",
        " * pose_model.c -- GENERATED by pc/pose/export_c.py. Do not hand-edit.",
        " *",
        f" * 4-class pose MLP, BatchNorm folded into the Linear layers, so the",
        " * firmware needs only multiply-add + relu + softmax -- no TVM, no",
        " * pose_model.a (which is Cortex-M4/v7E-M Thumb-only and cannot link",
        " * into this R5F/ARMv7-R image).",
        " *",
        f" * topology : {' -> '.join(str(s) for s in sizes)}  (relu after layers 0,1 only)",
        f" * input    : {FEATURE_COUNT} features x {WINDOW_SIZE} frames = {INPUT_SIZE},"
        " feature-major",
        f" *            x[j * {WINDOW_SIZE} + k] = frame k (k=0 oldest), feature j",
        f" * classes  : {', '.join(f'{i}={c}' for i, c in enumerate(CLASS_NAMES))}",
        f" * features : {', '.join(FEATURE_NAMES)}",
        f" * weights  : {tot} floats = {tot*4/1024:.1f} KB in .rodata.pose_model -> TCMB_RAM",
    ]
    if acc is not None:
        h.append(f" * accuracy : {acc*100:.1f}% (grouped-by-file 4-fold; NOT the random-row number)")
    h += [
        " *",
        " * CAVEAT: trained on TI's 6432 classes.zip (8 antennas, TI's mount).",
        " * Cleaned of the posz-dead recordings and the schema-leak features",
        " * (see pc/pose/dataset.py), but still 6432 geometry -- the 6844 z-offset",
        " * must be calibrated so a standing person reads posz ~ +0.33 m.",
        " */",
        "",
        "#include \"pose_mlp.h\"",
        "",
    ]
    out = ["\n".join(h)]
    for i, (W, b) in enumerate(layers):
        out.append(_arr(f"gPoseW{i}", W))
        out.append(_arr(f"gPoseB{i}", b))
    path.write_text("\n".join(out))
